services:
  # 1. Django Web Service
  - type: web
    name: arch-gym-web
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: arch-gym-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "*" # 실제 운영 시 .onrender.com 주소로 제한 권장
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: arch-gym-redis
          property: connectionString

  # 2. Celery Worker
  - type: worker
    name: arch-gym-worker
    env: python
    buildCommand: "./build.sh"
    startCommand: "celery -A config worker -l info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: arch-gym-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: arch-gym-redis
          property: connectionString

databases:
  - name: arch-gym-db
    plan: free

  # 3. Redis Instance
  - type: redis
    name: arch-gym-redis
    plan: free
    ipAllowList: [] # 기본적으로 내부 접속만 허용
